apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: otobo-backups
  name: otobo-backups
  namespace: otobo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
status: {}
